### ISSUE TITLE
write got error panic: failed to insert data: remoteAddr: 172.16.238.41:9000 -  DB::Exception (62): Empty query

### ISSUE THREAD

**Issue by harryhan1989** [vahid-sohrabloo/chconn#16]

**Comment by vahid-sohrabloo** [comment]
Can you share your code?

**Comment by harryhan1989** [comment]
the reason is my clickhouse table feilds using Decimal(30,3), when i use column.NewDecimal64(3, false) for Decimal(30,3) column, the issue will got. after i change the field type to  Decimal64(3) in clickhouse, running as expected.

**Comment by vahid-sohrabloo** [comment]
@harryhan1989  thanks. I know it's annoying that chconn doesn't check the ClickHouse column type and just reads data.
I'm working on the `v2` new version that uses Golang 1.18 generic. it's more simple and has some check these inputs to not happen these errors.
