### ISSUE TITLE
Support of nested arrays?

### ISSUE THREAD

**Issue by bgranvea** [vahid-sohrabloo/chconn#4]
I'm interested by your driver to improve insert performance (I'm currently using clickhouse-go) but I have some columns with type Array(Nullable(UInt32)) and Array(Array(Nullable(UInt32)). 

Are these types supported?

Thanks.

**Comment by vahid-sohrabloo** [comment]
Please pay attention, click house it's better to batch insert. you can insert any number of data with `Append` functions. and insert it with one Insert function.
also for better performance, it's better to use the column object again (you have to call the `Reset()` function after insert.)

**Comment by bgranvea** [comment]
thanks for the detailed response! I've done some basic tests, now I'm trying to integrate this in our code to see if performance are better.
