### ISSUE TITLE
Insert into Bool column

### ISSUE THREAD

**Issue by curt-hash** [vahid-sohrabloo/chconn#87]
Using the latest `v2` version, I get this error when attempting to insert `Column[bool]` into a `Bool` column:

```
mismatch column type: ClickHouse Type: Bool, column types: Int8|UInt8|Enum8
```

It seems like `chconn` validates the schema before insert, and it doesn't recognize `Bool`.

I understand that `Bool` is just an alias for `UInt8`, but this is handled transparently by other query interfaces. Is there some way to insert into a column of type `Bool` using `chconn`, or are there plans to support this?

**Comment by vahid-sohrabloo** [comment]
Thanks for reporting this issue.
It was fixed. and I released a new version.
